# !IMPORTANT - REMEMBER TO RESTART THE SERVER IN ORDER TO SEE CONFIG CHANGES!
# Site settings
title: Lucas J. Benda
description: Personal Website Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Lucas Benda
user_about: Ever since I can remember, technology and computers have fascinated me. I love to learn how things work and solve problems. I am constantly working to improve myself and those around me through education and experiences. This made my decision to study computer science and cybersecurity an easy one. I instantly was drawn to programming and creating new things. However, I also found that I value privacy and security, and I found a calling to protect this right for others and myself. I recognize that the need for this has expanded exponentially during the COVID-19 pandemic. However, I believe my education, skills, and experiences have prepared me to embrace the challenges of the future and excel my career in the Information Technology field.
# Have not found a way to include links in yml var text
user_experience: I will be assisting with their Cybersecurity and Hacking course, which was
    developed in partnership with Facebook to provide college students with hands-on experience in offensive security. The class
    focuses on web applications security, challenging students to learn to think like a hacker and exploit
    vulnerabilities, while also exploring how to build defensive capabilities into applications. 
user_title: Cybersecurity Risk Consultant
email: lucasjbenda@gmail.com
twitter_username: lukebenda3
github_username:  lukebenda

exclude: ['package.json', 'src' , 'node_modules']

# Build settings
plugins:
    - jekyll-feed
    - jekyll-seo-tag
