# Site settings
title: Lucas J. Benda
description: Personal Website Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lucas J. Benda
#user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Cybersecurity and Privacy Risk Consulttant
email: lucasjbenda@gmail.com
twitter_username: lukebenda3
github_username:  lukebenda
gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
