# Site settings
title: Lucas J. Benda
description: Personal Website Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Lucas J. Benda
user_description: 
user_title: Cybersecurity Risk Consultant
email: lucasjbenda@gmail.com
twitter_username: lukebenda3
github_username:  lukebenda

exclude: ['package.json', 'src' , 'node_modules']
